branches:
  only:
  - develop
language: python
cache: pip
python:
- 3.6
env:
  global:
    secure: IAX0vKxiHai+2VNv9fEXrH6FrRomhRn2F9u+vwbOpc9z29Y+XeQqtEW4hu2WqFDPAFMyk5lT5PW3VmwbhQIxCIyHd6/LZMcnPgcCjgFyCZaBVo15mLUIA+fDd6O7O+FqumE7gOaf/lbAv61IKsAuchv1AVDnULwEgdtY8a9RX1t/5X1kEQ+SYAVuvEWKVp2oZXlHfGoZKHpwakvp8Ci2w8Dh009zngNy2RckoH+/P4igy+3uTM1CMCOPuMP6J6ZRKSmQtEU7UUew0sTVRvbQzw9XKmOuuaInrv/UX03wSZ9nd4wxAsOfev5rq8lYiTcPPzbM8dkI987spx0qTVivKNbp+ylySNtH/6mjjDKA6YCQIOY9COFlXvLi7OjdrZKsAbx3BlIYpSR0MAXUM98nMz3A/iPAdul11CMQUzR8IYZphWk8MPQMXaH9l7qaqA55xP4rJ2BiAtM5jzUccH5koMwrrjkrDo1FYH+0uB2f7yp/bw2xnFxwMI7BeRhF/ksoozCWF7TMHzmQTFY70KZYMZ/u0GPuCqiqIIyHKHgCKY6nQgB03eQmBwYlHz9mMTnqZCcABGlzzaiZRXa/k87TEKOoCRmLigE2jzjC8jWjDw3rlBWFCVVdi2Pq3/yDa7hcHEywuBg32MT5b00+5knuC6BZXhIKoV26+M5nEqgBO88=

install:
- pip install -U pipenv
- pipenv install
- pelican-themes -i theme/pelican-themes/backdrop

script:
- cd src
- rst-lint content/*.rst
- make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  target-branch: master
  name: Travis CI
  local-dir: "./output"
  on:
    branch: develop
