language: python
# sudo: required
# dist: xenial
python:
- 3.6

branches:
  only:
  - develop

cache: pip

install:
- pip install -r requirements.txt
- pelican-themes -i pelican-bluedrop/bluedrop

script:
- cd src
- rst-lint content/*.rst
- pelican --version
- make publish

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  target-branch: master
  name: Travis CI
  local-dir: "./output"
  on:
    branch: develop
