language: python
sudo: required
dist: xenial
python:
- 3.7

branches:
  only:
  - develop

cache: pip

install:
- pip install -U pipenv
- pipenv install
- pelican-themes -i theme/pelican-themes/backdrop

script:
- cd src
- rst-lint content/*.rst
- pelican --version
- make publish

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  target-branch: master
  name: Travis CI
  local-dir: "./output"
  on:
    branch: develop
